import telebot

from telebot import types
from pars import kategory0,kategory1,kategory2,kategory3,kategory4,kategory5,kategory6,kategory7,kategory8,kategory9,kategory10,kategory11,kategory12,kategory13,kategory14,kategory15
from telebot.types import  ReplyKeyboardMarkup, InlineKeyboardMarkup, InlineKeyboardButton
from button import kb,ktgbtn,tvr

bot =  telebot.TeleBot('5632532758:AAF-PBBsRAIRkMhKnZHH-ExT8THMoVJ51YI')
@bot.message_handler(commands=['start'])
#Кнопки и приветствие
def start(message):
    bot.send_message(message.chat.id, 'Здравствуйте.Вас приветствует компания: ТОО"ВетЗащитаАзия"')
    markup=types.ReplyKeyboardMarkup(resize_keyboard=True)
    item1=types.KeyboardButton("Акции")
    markup.add(item1)
    item2=types.KeyboardButton("Товары")
    markup.add(item2)
    item3=types.KeyboardButton("Контакты")
    markup.add(item3)
    bot.send_message(message.chat.id,'Выберите на клавиатуре, что именно вас интересует?',reply_markup=markup)

@bot.message_handler(content_types=["text"])
def message_reply(message):
    if message.text=="Акции":
        img = open('1.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('2.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('3.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('4.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('5.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('6.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('7.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('8.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
        img = open('9.jpg', 'rb')
        bot.send_photo(message.chat.id, img, reply_markup = kb)
    if message.text=="Товары":
        bot.send_message(message.chat.id,'Выберите категорию:', reply_markup = tvr)
    if message.text=="Контакты":
        bot.send_message(message.chat.id, 'Наши контакты:' + '\n'+ 'Instagram' + '\n' +'*******' + '\n' + 'telegram:'+'\n'+'*******' + '\n'+'tel'+'\n')
      
@bot.callback_query_handler(func=lambda callback: callback.data)
def chek_callback_data(callback):
    if callback.data =='btn1':
        bot.send_message(callback.message.chat.id, 'Выберите ваш регион из списка:', reply_markup = ktgbtn)
    if callback.data =='mng1':
        bot.send_message(callback.message.chat.id, 'Для покупки товаров, свяжитесь с менеджером:')
        bot.send_message(callback.message.chat.id, 'Менеджер в вашем регионе:' '\n' 'Татьяна' + '\n' + '+77710949491')
    if callback.data =='mng2':
        bot.send_message(callback.message.chat.id, 'Для покупки товаров, свяжитесь с менеджером:')
        bot.send_message(callback.message.chat.id, 'Менеджер в вашем регионе:' '\n' 'Наталья' + '\n' + '+77710284600')
    if callback.data =='mng3':
        bot.send_message(callback.message.chat.id, 'Для покупки товаров, свяжитесь с менеджером:')
        bot.send_message(callback.message.chat.id, 'Менеджер в вашем регионе:' '\n' 'Марина' + '\n' + '+77710287768')
    if callback.data =='mng4':
        bot.send_message(callback.message.chat.id, 'Для покупки товаров, свяжитесь с менеджером:')
        bot.send_message(callback.message.chat.id, 'Менеджер в вашем регионе:' '\n' 'Сания' + '\n' + '+77054141830')
        #bot.send_photo(message.chat.id, img,  reply_markup = kb)
    if callback.data =='tcat0':
        stok = kategory0()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat1':
        stok = kategory1()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat2':
        stok = kategory2()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat3':
        stok = kategory3()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat4':
        stok = kategory4()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat5':
        stok = kategory5()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat6':
        stok = kategory6()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat7':
        stok = kategory7()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat8':
        stok = kategory8()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat9':
        stok = kategory9()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat10':
        stok = kategory10()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat11':
        stok = kategory11()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat12':
        stok = kategory12()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat13':
        stok = kategory13()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat14':
        stok = kategory14()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])
    if callback.data =='tcat15':
        stok = kategory15()
        bot.send_message(callback.message.chat.id,'/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/')
        bot.send_message(callback.message.chat.id,stok[0])
        bot.send_message(callback.message.chat.id,stok[1])
        bot.send_message(callback.message.chat.id,stok[2])
        bot.send_message(callback.message.chat.id,stok[3])
        bot.send_message(callback.message.chat.id,stok[4])
        bot.send_message(callback.message.chat.id,stok[5])
        bot.send_message(callback.message.chat.id,stok[6])
        bot.send_message(callback.message.chat.id,stok[7])
        bot.send_message(callback.message.chat.id,stok[8])
        bot.send_message(callback.message.chat.id,stok[9])
        bot.send_message(callback.message.chat.id,stok[10])
        bot.send_message(callback.message.chat.id,stok[11])
        bot.send_message(callback.message.chat.id,stok[12])
        bot.send_message(callback.message.chat.id,stok[13])
        bot.send_message(callback.message.chat.id,stok[14])    
        
bot.infinity_polling()