from telebot.types import  ReplyKeyboardMarkup, InlineKeyboardMarkup, InlineKeyboardButton
from telebot import types
kb = types.InlineKeyboardMarkup(row_width=1)
btn1 = types.InlineKeyboardButton(text='Купить по акции.', callback_data='btn1')
kb.add(btn1)

ktgbtn = types.InlineKeyboardMarkup(row_width=1)
btnr1 = types.InlineKeyboardButton(text='Алма-аты', callback_data='mng1')
btnr2 = types.InlineKeyboardButton(text='Атырау', callback_data='mng1')
btnr3 = types.InlineKeyboardButton(text='Астана', callback_data='mng2')
btnr4 = types.InlineKeyboardButton(text='Актюбинск', callback_data='mng4')
btnr5 = types.InlineKeyboardButton(text='Караганда', callback_data='mng3')
btnr6 = types.InlineKeyboardButton(text='Костанай', callback_data='mng2')
btnr7 = types.InlineKeyboardButton(text='Кокщетав', callback_data='mng3')
btnr8 = types.InlineKeyboardButton(text='Лисаковск', callback_data='mng2')
btnr9 = types.InlineKeyboardButton(text='Павлодар', callback_data='mng3')
btnr10 = types.InlineKeyboardButton(text='Петропавловск', callback_data='mng3')
btnr11 = types.InlineKeyboardButton(text='Рудный', callback_data='mng2')
btnr12 = types.InlineKeyboardButton(text='Семей', callback_data='mng3')
btnr13 = types.InlineKeyboardButton(text='Тараз', callback_data='mng4')
btnr14 = types.InlineKeyboardButton(text='Уральск', callback_data='mng4')
btnr15 = types.InlineKeyboardButton(text='Усть-каменогорск', callback_data='mng2')
btnr16 = types.InlineKeyboardButton(text='Щучинск', callback_data='mng3')
btnr17 = types.InlineKeyboardButton(text='Шымкент', callback_data='mng4')
ktgbtn.add(btnr1,btnr2,btnr3,btnr4,btnr5,btnr6,btnr7,btnr8,btnr9,btnr10,btnr11,btnr12,btnr13,btnr14,btnr15,btnr16,btnr17)


tvr = types.InlineKeyboardMarkup(row_width=1)
cat0 = types.InlineKeyboardButton(text='Акушерско-гинекологические', callback_data='tcat0')
cat1 = types.InlineKeyboardButton(text='Антибактериальные и жаропонижающие ', callback_data='tcat1')
cat2 = types.InlineKeyboardButton(text='Антигельминтные препараты', callback_data='tcat2')
cat3 = types.InlineKeyboardButton(text='Вакцины и сыворотки', callback_data='tcat3')
cat4 = types.InlineKeyboardButton(text='Витамино-минеральные препараты', callback_data='tcat4')
cat5 = types.InlineKeyboardButton(text='Гепатопротекторы', callback_data='tcat5')
cat6 = types.InlineKeyboardButton(text='Гомеопатические препараты', callback_data='tcat6')
cat7 = types.InlineKeyboardButton(text='Гормональные препараты', callback_data='tcat7')
cat8 = types.InlineKeyboardButton(text='Дезинфекция, дезинсекиця, дератизация', callback_data='tcat8')
cat9 = types.InlineKeyboardButton(text='Иммуномодуляторы', callback_data='tcat9')
cat10 = types.InlineKeyboardButton(text='Инсектоакарицидные препараты (от блох, вшей. клещей)', callback_data='tcat10')
cat11 = types.InlineKeyboardButton(text='Инструменты', callback_data='tcat11')
cat12 = types.InlineKeyboardButton(text='Кокцидиостатики', callback_data='tcat12')
cat13 = types.InlineKeyboardButton(text='Мази, крема, спреи', callback_data='tcat13')
cat14 = types.InlineKeyboardButton(text='Регуляции половой охоты', callback_data='tcat14')
cat15 = types.InlineKeyboardButton(text='Средства симптоматической терапии', callback_data='tcat15')
tvr.add(cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,cat11,cat12,cat13,cat14,cat15)